name: Local Docker Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy Docker Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}      
          key: ${{ secrets.EC2_SSH_KEY }}        
          port: ${{ secrets.EC2_PORT }}          
          script: |
            cd ~/Scientific-Calculator || exit 1
            git pull origin main

            echo "Stopping and removing old container (if exists)..."
            docker rm -f calculator || true

            echo "Removing old image (if exists)..."
            docker rmi -f sci-calci || true

            echo "Building Docker image..."
            docker build -t sci-calci .

            echo "Running Docker container..."
            docker run -d -p 3000:80 --name calculator sci-calci
