name: Local Docker Deploy

on:
  push:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove existing Docker container and image
        run: |
          docker rm -f calculator || true
          docker rmi -f sci-calci || true

      - name: Build Docker image
        run: docker build -t sci-calci .

      - name: Run Docker container
        run: docker run -d -p 3000:80 --name calculator sci-calci
